// This file is auto-generated and will be overwritten
export type StateIds =
  | 'list'
  | 'list.unselected'
  | 'list.selected'
  | 'modal'
  | 'modal.closed'
  | 'modal.open'
  | 'posts'
  | 'posts.initial'
  | 'posts.idle'
  | 'posts.testing'
  | 'posts.loading'
  | 'posts.error'
  | 'count'
  | '/'
  | '/.posts'
  | '/.count'
  | '/second'
  | '/second.count'
  | '/pizza'
  | '/pizza.modal';
