// This file is auto-generated by generate-types.ts and will be overwritten
export type StateIds =
  | 'list'
  | 'list.unselected'
  | 'list.selected'
  | 'modal'
  | 'modal.closed'
  | 'modal.help'
  | 'modal.open'
  | 'posts'
  | 'posts.initial'
  | 'posts.idle'
  | 'posts.loading'
  | 'posts.error'
  | 'count';
