/*
  This file is being used to generate the types for state.matches()
  Xstate does not have the capability to type check it
  file output is in ./src/app/machines/types.ts
*/
import fs from 'node:fs';
import { idMap } from 'machines/machine-utils';
import service from 'machines/router.machine';

const filePath = './src/app/machines/states.generated.ts';

const ids = Object.values(idMap)
  .flat()
  .filter((o) => !o.startsWith('/'));

// Generate stateIds
const content = fs.readFileSync(filePath, {
  encoding: 'utf-8',
});

const output = `// This file is auto-generated by generate-types.ts and will be overwritten
export type StateIds =\n  | '${Array.from(ids).join("'\n  | '")}';\n`;

if (content !== output) {
  fs.writeFileSync(filePath, output);
}

test.todo('', () => expect(service).toBeDefined());
